name: flutter_feather_icons
description: flutter package consisting of icons from the feather team
version: 1.0.0
author: Nikhil Anand <nick.muj.programmer@gmail.com>
homepage: https://github.com/muj-programmer/flutter_feather_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^2.0.1

flutter:
  fonts:
    - family: FeatherIcons
      fonts:
        - asset: fonts/feather.ttf
