name: flutter_feather_icons
description: A new Flutter package project.
version: 0.0.1
author: Nikhil Anand <nick.muj.programmer@gmail.com>
homepage: https://github.com/muj-programmer/flutter_feather_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: FeatherIcons
      fonts:
        - asset: lib/src/fonts/feather.ttf
